### ISSUE TITLE
help

### ISSUE THREAD

**Issue by phamtruong010** [nghinv-software/react-native-dropdown-alert#1]
![Simulator Screen Shot - iPhone 11 - 2021-03-08 at 14 50 33](https://user-images.githubusercontent.com/51196083/110290751-b7251600-801d-11eb-9e3e-0e9abf068c23.png)

**Comment by Nghi-NV** [comment]
@phamtruong010 The library use react-native-reanimated v2.It's not support react-native-reanimated v1
